server:
  port: 8770

spring:
  application:
    name: server-zuul
  zipkin:
      base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: server-ribbon
    api-b:
      path: /api-b/**
      serviceId: server-feign