server:
  port: 8765

spring:
  application:
    name: server-feign
  zipkin:
      base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/